### ISSUE TITLE
KeyError: key not found: :secret_key_base

### ISSUE THREAD

**Issue by Perdixo** [timecop-app/timecop-api#4]
When running `bin/setup`, i have the following error 

```
== Installing dependencies ==
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
The Gemfile's dependencies are satisfied

== Preparing database ==
rails aborted!
KeyError: key not found: :secret_key_base
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/activesupport-6.0.1/lib/active_support/encrypted_configuration.rb:11:in `fetch'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/activesupport-6.0.1/lib/active_support/encrypted_configuration.rb:11:in `fetch'
/Users/perdixo/Downloads/twackr-master/timecop-api/config/initializers/devise.rb:306:in `block (2 levels) in <top (required)>'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/devise-jwt-0.6.0/lib/devise/jwt.rb:20:in `jwt'
/Users/perdixo/Downloads/twackr-master/timecop-api/config/initializers/devise.rb:305:in `block in <top (required)>'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/devise-4.7.1/lib/devise.rb:311:in `setup'
/Users/perdixo/Downloads/twackr-master/timecop-api/config/initializers/devise.rb:9:in `<top (required)>'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:319:in `load'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:319:in `block in load'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:319:in `load'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/engine.rb:667:in `block in load_config_initializer'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/activesupport-6.0.1/lib/active_support/notifications.rb:182:in `instrument'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/engine.rb:666:in `load_config_initializer'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/engine.rb:624:in `block (2 levels) in <class:Engine>'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/engine.rb:623:in `each'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/engine.rb:623:in `block in <class:Engine>'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/initializable.rb:32:in `instance_exec'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/initializable.rb:32:in `run'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/initializable.rb:61:in `block in run_initializers'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/initializable.rb:50:in `each'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/initializable.rb:50:in `tsort_each_child'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/initializable.rb:60:in `run_initializers'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/application.rb:363:in `initialize!'
/Users/perdixo/Downloads/twackr-master/timecop-api/config/environment.rb:7:in `<top (required)>'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:23:in `require'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `block in require'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:291:in `load_dependency'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/activesupport-6.0.1/lib/active_support/dependencies.rb:325:in `require'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/application.rb:339:in `require_environment!'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/application.rb:515:in `block in run_tasks_blocks'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/command.rb:48:in `invoke'
/Users/perdixo/.rvm/gems/ruby-2.6.4/gems/railties-6.0.1/lib/rails/commands.rb:18:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
Tasks: TOP => db:prepare => db:load_config => environment
(See full trace by running task with --trace)

== Command ["bin/rails db:prepare"] failed ==
```

**Comment by guillaumebriday** [comment]
Yes, as I mentioned in the readme you need to run : `rm config/credentials.yml.enc && bundle exec rails credentials:edit`

I didn't find a way to work with credentials on an open source project. If you have any idea that would be great!

Thanks
